name: Create File on Push

on:
  push:
    branches:
      - main # Change this to the branch where you want to trigger the action

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create File
        run: |
          # Generate content for the new file (e.g., a timestamp)
          CONTENT="File created on $(date)"

          # Set the filename and path
          FILENAME="newfile-$(date +%Y%m%d%H%M%S).txt"

          # Create the file with the content
          echo "$CONTENT" > "$FILENAME"

          # Add, commit, and push the new file
          git add "$FILENAME"
          git commit -m "Add $FILENAME"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
