name: Access Another Repository

on:
  push:
    branches:
      - main

jobs:
  access-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Access Another Repository
        run: |
          # Set up the Personal Access Token (MDFILEINTERLOCK)
          MDFILEINTERLOCK="${{ secrets.MDFILEINTERLOCK }}"

          # Set the repository URL
          REPO_URL="https://github.com/AwesomeYelim/AwesomeYelim.git"

          # Clone the repository using the PAT
          git clone "$REPO_URL"

          # Now you have access to the cloned repository
        env:
          MDFILEINTERLOCK: ${{ secrets.MDFILEINTERLOCK }}
