name: Access Another Repository

on:
  push:
    branches:
      - main

jobs:
  access-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: create textFile
        run: echo "A beautiful day !!" > [filename].txt

        env:
          API_TOKEN_GITHUB: ${{ secrets.MDFILEINTERLOCK }}
