name: Access Another Repository

on:
  push:
    branches:
      - main

jobs:
  access-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Access Another Repository
        run: |
          FILENAME=[filename].txt

          echo "A beautiful day !!" > [filename].txt

          # Add, commit, and push the new file
          git add "$FILENAME"
          git commit -m "Add $FILENAME"
          git push
        env:
          MDFILEINTERLOCK: ${{ secrets.MDFILEINTERLOCK }}
