name: Access Another Repository

on:
  push:
    branches:
      - main

jobs:
  access-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Access Another Repository
        run: mkdir output.md
        env:
          MDFILEINTERLOCK: ${{ secrets.MDFILEINTERLOCK }}
